import '@storybook/addon-knobs/register'
import '@storybook/addon-actions/register'
import '@storybook/addon-a11y/register'
import '@storybook/addon-viewport/register'
import '@fs/storybook-addons/dist/grid/register'
import '@fs/storybook-addons/dist/locale-switcher/register'
import '@fs/storybook-addons/dist/sign-in/register'
import '@fs/storybook-addons/dist/env/register'
